---
# This is a sample database file for the DataMapper ORM
development: &defaults
  # These are the settings for repository :default
  adapter: mysql
  host: 127.0.0.1 
  username: stripes 
  password: XjLNRvE.:sPhWsWR
  database: wsj_development

 
  # Add more repositories
  # repositories:
  #   repo1:
  #     adapter:  sqlite3
  #     database: sample_1_development.db
  #   repo2:
  #     ...
 
test:
  <<:       *defaults
  database: wsj_test
 
  # repositories:
  #   repo1:
  #     database: sample_1_test.db
 
production:
  <<:       *defaults
  database: wsj_production
 
  # repositories:
  #   repo1:
  #     database: sample_production.db
 
rake:
  <<: *defaults