  - name   : "Today's Paper"
    display: 1  
    feeds  :
    - name : "Page One"
      url  : "http://online.wsj.com/page/us_in_todays_paper.html"
      type : "PageOneageOne"
      
  - name   : "Opinion"
    display: 1  
    feeds  :
    - name : "Opinion"
      url  : "http://online.wsj.com/page/us_in_todays_paper.html"
      type : "FeedOpinion"
      
  - name   : "Money & Investing"
    display: 1  
    feeds  :
    - name : "Money & Investing"
      url  : "http://online.wsj.com/page/us_in_todays_paper.html"
      type : "FeedMoneyInvesting"        
      
  - name   : "What's News"
    display: 0
    feeds  :
    - name : "What's News"
      url  : "http://online.wsj.com/xml/rss/3_7011.xml"
        
  - name   : "Life & Entertainment"
    display: 1  
    feeds  :
    - name : "Lifestyle"
      url  : "http://online.wsj.com/xml/rss/3_7201.xml"
    - name : "On Style"
      url  : "http://online.wsj.com/xml/rss/3_7336.xml"
      
  - name   : "Sports"
    display: 1  
    feeds  :
    - name : "Sports"
      url  : "http://online.wsj.com/xml/rss/3_7493.xml"
      
  - name   : "Columnists"
    display: 1  
    feeds  : 
    - name : "Numbers Guy"
      url  : "http://online.wsj.com/xml/rss/3_7111.xml"
    - name : "Numbers Guy Blog"
      url  : "http://feeds.wsjonline.com/wsj/numbersguy/feed"
      
  - name   : "Most Viewed"
    display: 1  
    feeds  :
    - name : "Most Viewed Today"
      url  : "http://online.wsj.com/xml/rss/3_7198.xml"
    - name : "Most Viewed This Week"
      url  :  "http://online.wsj.com/xml/rss/3_7251.xml"
    
  - name: "Search"
    display: 0